language: EN
strict: false
# output:
#   file_path: results.csv
#   format: CSV
sast:
  include:
    - .
  exclude: # Optional: paths to exclude from scanning
    - node_modules
    - vendor

sca:
  include:
    - .
  exclude: # Optional: paths to exclude from scanning
    - vendor/

ss:
  include:
    - . # paths to scan (default: entire repo)
  exclude:
    - tests/ # paths to skip
