name: SCA
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fluidattacks/sca-action@1.2.0
        id: scan
        with:
          scan_config_path: .github/config.yaml

      - name: Rename CSV
        if: always()
        run: mv results.csv sca-results.csv

      - name: Upload CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sca-results
          path: sca-results.csv
