name: SECRET_SCAN
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 8 * * 1" # optional: weekly full scan every Monday at 8am

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required: full history enables differential scanning

      - uses: fluidattacks/ss-action@0.2.0 # Use latest released version
        id: scan
        with:
          scan_config_path: .github/config.yaml

      - name: Rename CSV
        if: always()
        run: mv results.csv ss-results.csv

      - name: Upload CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ss-results
          path: ss-results.csv
